/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Constants for home.
 */
export class HomeConstants {
  /**
   * Column component spacing.
   */
  static readonly COLUMN_SPACE: string = '12vp';

  /**
   * Text transparency.
   */
  static readonly TEXT_OPACITY: number = 0.6;

  /**
   * Bottom bar height.
   */
  static readonly BOTTOM_BAR_HEIGHT: number = 72;

  /**
   * Tab icon size.
   */
  static readonly TAB_ICON_SIZE: number = 28;

  /**
   * Tab text size.
   */
  static readonly TAB_TEXT_SIZE: number = 13;

  /**
   * Tab icon margin.
   */
  static readonly TAB_ICON_MARGIN: number = 6;

  /**
   * Tab padding.
   */
  static readonly TAB_PADDING: number = 10;

  /**
   * Bottom bar background color.
   */
  static readonly BOTTOM_BAR_COLOR: string = '#3a3a5a';

  /**
   * Card pressed opacity.
   */
  static readonly CARD_PRESSED_OPACITY: number = 0.8;
}